import { FONTS } from './fonts';

export const COLORS = {
  PRIMARY: '#4c5dab',
  PRIMARY_DARK: '#3a4a8a',
  SECONDARY: '#809fff',
  SECONDARY_LIGHT: '#a8b8ff',
  TEXT_PRIMARY: '#2c3e50',
  TEXT_SECONDARY: '#7f8c8d',
  TEXT_LIGHT: '#95a5a6',
  WHITE: '#ffffff',
  LIGHT_GRAY: '#f8f9fa',
  GRAY: '#ecf0f1',
  DARK_GRAY: '#34495e',
  BORDER: '#e9ecef',
  SUCCESS: '#27ae60',
  WARNING: '#f39c12',
  ERROR: '#e74c3c',
  SHADOW: 'rgba(0, 0, 0, 0.1)',
  CARD_BG: 'rgba(255, 255, 255, 0.95)',
  GRADIENT_START: '#667eea',
  GRADIENT_END: '#764ba2',
};

export const HEADER_STYLES = {
  headerTitleStyle: {
    fontSize: 22,
    fontFamily: FONTS.NUNITO_SEMIBOLD,
    color: COLORS.TEXT_PRIMARY,
  },
  headerTitleAlign: "center",
  headerStyle: {
    backgroundColor: COLORS.WHITE,
    elevation: 0,
    shadowOpacity: 0,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.BORDER,
  },
  headerTintColor: COLORS.PRIMARY,
};

export const COMMON_STYLES = {
  mainContainer: {
    flex: 1,
    backgroundColor: COLORS.LIGHT_GRAY,
  },
  contentContainer: {
    flex: 1,
    paddingHorizontal: 24,
    paddingVertical: 20,
  },
  mainHeader: {
    fontSize: 28,
    color: COLORS.TEXT_PRIMARY,
    fontFamily: FONTS.NUNITO_SEMIBOLD,
    marginBottom: 12,
    textAlign: 'center',
  },
  subHeader: {
    fontSize: 20,
    color: COLORS.TEXT_SECONDARY,
    fontFamily: FONTS.NUNITO_SEMIBOLD,
    marginBottom: 12,
  },
  paraStyle: {
    textAlign: "center",
    fontSize: 16,
    color: COLORS.TEXT_SECONDARY,
    lineHeight: 24,
    fontFamily: FONTS.JOSEFIN_REGULAR,
    marginBottom: 16,
  },
  buttonStyle: {
    backgroundColor: COLORS.PRIMARY,
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 24,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: COLORS.SHADOW,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  buttonSecondary: {
    backgroundColor: COLORS.SECONDARY,
    borderRadius: 16,
    paddingVertical: 16,
    paddingHorizontal: 24,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: COLORS.SHADOW,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 6,
  },
  buttonText: {
    fontSize: 16,
    color: COLORS.WHITE,
    fontFamily: FONTS.JOSEFIN_MEDIUM,
    fontWeight: '600',
  },
  cardContainer: {
    backgroundColor: COLORS.CARD_BG,
    borderRadius: 20,
    padding: 24,
    marginVertical: 12,
    shadowColor: COLORS.SHADOW,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 8,
    borderWidth: 1,
    borderColor: COLORS.BORDER,
  },
  inputContainer: {
    marginBottom: 20,
  },
  inputStyle: {
    backgroundColor: COLORS.WHITE,
    borderWidth: 1,
    borderColor: COLORS.BORDER,
    borderRadius: 16,
    paddingHorizontal: 20,
    paddingVertical: 16,
    fontSize: 16,
    fontFamily: FONTS.JOSEFIN_REGULAR,
    color: COLORS.TEXT_PRIMARY,
    shadowColor: COLORS.SHADOW,
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  inputLabel: {
    fontSize: 16,
    color: COLORS.TEXT_PRIMARY,
    fontFamily: FONTS.NUNITO_SEMIBOLD,
    marginBottom: 8,
  },
  divider: {
    height: 1,
    backgroundColor: COLORS.BORDER,
    marginVertical: 20,
  },
  badge: {
    backgroundColor: COLORS.SECONDARY_LIGHT,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
    alignSelf: 'flex-start',
  },
  badgeText: {
    color: COLORS.PRIMARY,
    fontSize: 12,
    fontFamily: FONTS.JOSEFIN_MEDIUM,
    fontWeight: '600',
  },
  priceTag: {
    backgroundColor: COLORS.SUCCESS,
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    alignSelf: 'flex-start',
  },
  priceText: {
    color: COLORS.WHITE,
    fontSize: 16,
    fontFamily: FONTS.NUNITO_SEMIBOLD,
    fontWeight: '600',
  },
  socialButton: {
    backgroundColor: COLORS.WHITE,
    borderRadius: 16,
    padding: 20,
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: COLORS.SHADOW,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
    borderWidth: 1,
    borderColor: COLORS.BORDER,
  },
  profileImage: {
    width: 120,
    height: 120,
    borderRadius: 60,
    borderWidth: 4,
    borderColor: COLORS.WHITE,
    shadowColor: COLORS.SHADOW,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.3,
    shadowRadius: 16,
    elevation: 8,
  },
  menuContainer: {
    backgroundColor: COLORS.WHITE,
    borderRadius: 20,
    padding: 24,
    marginHorizontal: 0,
    marginVertical: 0,
    shadowColor: COLORS.SHADOW,
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.15,
    shadowRadius: 16,
    elevation: 8,
  },
}; 