const Courses = [{
    id: "1",
    title: "Complete JEE Mains Bootcamp",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum id pretium quam, nec tincidunt mauris. Donec aliquam diam urna, quis lobortis enim dignissim blandit. Sed consectetur pretium leo sed posuere. Aenean id porttitor quam. Nulla at eros eu nisl vehicula.",
    course1: "Physics",
    course2: "Chemistry",
    course3: "Maths",
    price: 3000,
    image: require("../../assets/jeemain.jpg"),
},
{
    id: "2",
    title: "Complete JEE Mains Bootcamp",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum id pretium quam, nec tincidunt mauris. Donec aliquam diam urna, quis lobortis enim dignissim blandit. Sed consectetur pretium leo sed posuere. Aenean id porttitor quam. Nulla at eros eu nisl vehicula.",
    course1: "Physics",
    course2: "Chemistry",
    course3: "Maths",
    price: 3000,
    image: require("../../assets/jeemain.jpg"),
},
{
    id: "3",
    title: "Complete JEE Mains Bootcamp",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum id pretium quam, nec tincidunt mauris. Donec aliquam diam urna, quis lobortis enim dignissim blandit. Sed consectetur pretium leo sed posuere. Aenean id porttitor quam. Nulla at eros eu nisl vehicula.",
    course1: "Physics",
    course2: "Chemistry",
    course3: "Maths",
    price: 3000,
    image: require("../../assets/jeemain.jpg"),
},
{
    id: "4",
    title: "Complete JEE Mains Bootcamp",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum id pretium quam, nec tincidunt mauris. Donec aliquam diam urna, quis lobortis enim dignissim blandit. Sed consectetur pretium leo sed posuere. Aenean id porttitor quam. Nulla at eros eu nisl vehicula.",
    course1: "Physics",
    course2: "Chemistry",
    course3: "Maths",
    price: 3000,
    image: require("../../assets/jeemain.jpg"),
},
{
    id: "5",
    title: "Complete JEE Mains Bootcamp",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum id pretium quam, nec tincidunt mauris. Donec aliquam diam urna, quis lobortis enim dignissim blandit. Sed consectetur pretium leo sed posuere. Aenean id porttitor quam. Nulla at eros eu nisl vehicula.",
    course1: "Physics",
    course2: "Chemistry",
    course3: "Maths",
    price: 3000,
    image: require("../../assets/jeemain.jpg"),
},
{
    id: "6",
    title: "Complete JEE Mains Bootcamp",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum id pretium quam, nec tincidunt mauris. Donec aliquam diam urna, quis lobortis enim dignissim blandit. Sed consectetur pretium leo sed posuere. Aenean id porttitor quam. Nulla at eros eu nisl vehicula.",
    course1: "Physics",
    course2: "Chemistry",
    course3: "Maths",
    price: 3000,
    image: require("../../assets/jeemain.jpg"),
},
{
    id: "7",
    title: "Complete JEE Mains Bootcamp",
    description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Vestibulum id pretium quam, nec tincidunt mauris. Donec aliquam diam urna, quis lobortis enim dignissim blandit. Sed consectetur pretium leo sed posuere. Aenean id porttitor quam. Nulla at eros eu nisl vehicula.",
    course1: "Physics",
    course2: "Chemistry",
    course3: "Maths",
    price: 3000,
    image: require("../../assets/jeemain.jpg"),
},
];

export default Courses;